spring.application.name=isera-it-asset-management

spring.datasource.url=jdbc:mysql://localhost:3307/isera_asset_management
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

security.jwt.secret=change-this-development-secret-key-to-a-long-random-value-123456789
security.jwt.expiration=900000

security.jwt.refresh-expiration=2592000